# Generated by Django 3.0.7 on 2020-06-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200615_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('NOTPAID', 'Not Paid'), ('PARTPAID', 'Partial Paid'), ('PAID', 'Paid')], max_length=10, null=True),
        ),
    ]
