# Generated by Django 3.0.7 on 2020-06-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200615_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
    ]
